"""Column name changed in the table chunks (chunk-content)

Revision ID: 7e2eba868d0b
Revises: 6690e603c8ce
Create Date: 2026-09-26 17:40:23.726004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2eba868d0b'
down_revision: Union[str, Sequence[str], None] = '6690e603c8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('chunks', 'chunk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('chunks', 'content')
    # ### end Alembic commands ###
